// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class TestEntity
{
	private final IMendixObject testEntityMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.TestEntity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SomeNumber("SomeNumber");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public TestEntity(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.TestEntity"));
	}

	protected TestEntity(IContext context, IMendixObject testEntityMendixObject)
	{
		if (testEntityMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.TestEntity", testEntityMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.TestEntity");

		this.testEntityMendixObject = testEntityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new TestEntity(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static myfirstmodule.proxies.TestEntity create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "MyFirstModule.TestEntity");
		return new myfirstmodule.proxies.TestEntity(context, mendixObject);
	}

	/**
	 * @deprecated Use 'TestEntity.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.TestEntity initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.TestEntity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.TestEntity initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TestEntity(context, mendixObject);
	}

	public static myfirstmodule.proxies.TestEntity load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TestEntity.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.TestEntity> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.TestEntity> result = new java.util.ArrayList<myfirstmodule.proxies.TestEntity>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.TestEntity" + xpathConstraint))
			result.add(myfirstmodule.proxies.TestEntity.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SomeNumber
	 */
	public final Integer getSomeNumber()
	{
		return getSomeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of SomeNumber
	 */
	public final Integer getSomeNumber(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.SomeNumber.toString());
	}

	/**
	 * Set value of SomeNumber
	 * @param somenumber
	 */
	public final void setSomeNumber(Integer somenumber)
	{
		setSomeNumber(getContext(), somenumber);
	}

	/**
	 * Set value of SomeNumber
	 * @param context
	 * @param somenumber
	 */
	public final void setSomeNumber(IContext context, Integer somenumber)
	{
		getMendixObject().setValue(context, MemberNames.SomeNumber.toString(), somenumber);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return testEntityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TestEntity that = (myfirstmodule.proxies.TestEntity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.TestEntity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().getGuid();
	}
}
