// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public enum RuntimeMode
{
	Testing(new String[][] { new String[] { "en_US", "Testing" }, new String[] { "nl_NL", "Test" } }),
	Acceptance(new String[][] { new String[] { "en_US", "Acceptance" }, new String[] { "nl_NL", "Acceptatie" } }),
	Production(new String[][] { new String[] { "en_US", "Production" }, new String[] { "nl_NL", "Productie" } });

	private java.util.Map<String,String> captions;

	private RuntimeMode(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
