// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public enum UserAmountType
{
	Specified(new String[][] { new String[] { "en_US", "Specified" }, new String[] { "nl_NL", "Gespecificeerd" } }),
	Unlimited(new String[][] { new String[] { "en_US", "Unlimited" }, new String[] { "nl_NL", "Onbeperkt" } });

	private java.util.Map<String,String> captions;

	private UserAmountType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
