// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public enum LicenseType
{
	Subscription(new String[][] { new String[] { "en_US", "Subscription" }, new String[] { "nl_NL", "Abonnement" } }),
	Perpetual(new String[][] { new String[] { "en_US", "Perpetual" }, new String[] { "nl_NL", "Oneindig" } });

	private java.util.Map<String,String> captions;

	private LicenseType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
