// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the Microflows for the MyFirstModule module

	public static myfirstmodule.proxies.Circle circleDataSource(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MyFirstModule.CircleDataSource", params);
			return result == null ? null : myfirstmodule.proxies.Circle.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void onchangeMicroflow(IContext context, myfirstmodule.proxies.Circle _circle)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Circle", _circle == null ? null : _circle.getMendixObject());
			Core.execute(context, "MyFirstModule.onchangeMicroflow", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}